CREATE TABLE IF NOT EXISTS hpi (
    area_code                     TEXT NOT NULL,
    region_name                   TEXT NOT NULL,
    period_date                   TEXT NOT NULL,
    average_price                 REAL,
    price_index                   REAL,
    index_sa                      REAL,
    change_1m_pct                 REAL,
    change_12m_pct                REAL,
    average_price_sa              REAL,
    sales_volume                  INTEGER,
    detached_price                REAL,
    detached_index                REAL,
    detached_change_1m_pct        REAL,
    detached_change_12m_pct       REAL,
    semi_detached_price           REAL,
    semi_detached_index           REAL,
    semi_detached_change_1m_pct   REAL,
    semi_detached_change_12m_pct  REAL,
    terraced_price                REAL,
    terraced_index                REAL,
    terraced_change_1m_pct        REAL,
    terraced_change_12m_pct       REAL,
    flat_price                    REAL,
    flat_index                    REAL,
    flat_change_1m_pct            REAL,
    flat_change_12m_pct           REAL,
    cash_price                    REAL,
    cash_index                    REAL,
    cash_change_1m_pct            REAL,
    cash_change_12m_pct           REAL,
    cash_sales_volume             REAL,
    mortgage_price                REAL,
    mortgage_index                REAL,
    mortgage_change_1m_pct        REAL,
    mortgage_change_12m_pct       REAL,
    mortgage_sales_volume         REAL,
    ftb_price                     REAL,
    ftb_index                     REAL,
    ftb_change_1m_pct             REAL,
    ftb_change_12m_pct            REAL,
    foo_price                     REAL,
    foo_index                     REAL,
    foo_change_1m_pct             REAL,
    foo_change_12m_pct            REAL,
    new_price                     REAL,
    new_index                     REAL,
    new_change_1m_pct             REAL,
    new_change_12m_pct            REAL,
    new_sales_volume              REAL,
    old_price                     REAL,
    old_index                     REAL,
    old_change_1m_pct             REAL,
    old_change_12m_pct            REAL,
    old_sales_volume              REAL,
    PRIMARY KEY (area_code, period_date)
);

CREATE TABLE IF NOT EXISTS ppd (
    -- unique_id is NOT a PRIMARY KEY here on purpose: a TEXT primary key
    -- forces SQLite to maintain a B-tree uniqueness index on every single
    -- insert, which gets progressively slower as the table grows (the
    -- dominant cost at 31M rows). The uniqueness index is instead built
    -- once, after bulk load, as idx_ppd_unique_id (see schema_indexes.sql) -
    -- exactly like every other ppd index.
    unique_id      TEXT NOT NULL,
    price_paid     INTEGER,
    deed_date      TEXT,
    postcode       TEXT,
    property_type  TEXT,
    new_build      TEXT,
    estate_type    TEXT,
    saon           TEXT,
    paon           TEXT,
    street         TEXT,
    locality       TEXT,
    town           TEXT,
    district       TEXT,
    county         TEXT,
    ppd_category   TEXT,
    record_status  TEXT
);
